# Dependencies
# 必须改用 kramdown，GitHub Pages 不再支持 redcarpet
markdown:         kramdown
# 必须改用 rouge，GitHub Pages 不再支持 pygments
highlighter:      rouge

# Permalinks
permalink:        pretty
# 必须改为 false，解决你日志里的那个 Warning
relative_permalinks: false

# Setup
title:            Zhihang's Blog
tagline:          'Postdoc at University of Houston'
description:      'Research and Thoughts'
url:              "https://zhihangxu.github.io"
baseurl:          "/blog"

author:
  name:           'Zhihang Xu'
  url:            https://zhihangxu.github.io

paginate:         5

# 让 GitHub 知道不要加载默认主题
theme: null
